/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package localtransportmanagment.system;

/**
 *
 * @author USER
 */
public class home extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_Customerid = new javax.swing.JTextField();
        t_Orderid = new javax.swing.JTextField();
        t_Status = new javax.swing.JTextField();
        t_Driver_id = new javax.swing.JTextField();
        t_location = new javax.swing.JTextField();
        t_Vehicleno = new javax.swing.JTextField();
        t_TrackingNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tracking No");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel3.setText("Customer id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setText("Order id");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setText("Status");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setText("Driver id");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setText("Customer Location");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel8.setText("vehicle No");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel2.add(t_Customerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 20));
        jPanel2.add(t_Orderid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, -1));
        jPanel2.add(t_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));
        jPanel2.add(t_Driver_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, -1));
        jPanel2.add(t_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, -1));
        jPanel2.add(t_Vehicleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 120, -1));

        t_TrackingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TrackingNoActionPerformed(evt);
            }
        });
        jPanel2.add(t_TrackingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 310, 290));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void t_TrackingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TrackingNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TrackingNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //add
    // TODO add your handling code here:
        String Customer id =t_Customerid.getText();
        String Order id = t_Orderid.getText();
        String status = t_Status.getText();
        String Driver id =t_Customerid.getText();
        String Customer Location= t_location.getText();
        String vehicle No = t_phone.getText();
        String Tracking No = t_phone.getText();
        
        
        try {
             System.out.println("4");
            Connection con = db.mycon();
            String sql = "insert into sliit.student (stname,address,phone) values (?,?,?)";
             System.out.println("5");
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, name);
            pst.setString(2, address);
            pst.setString(3, phone);
            
             System.out.println("6");
            int updatedRowCount = pst.executeUpdate();
            
             System.out.println("7");
            JOptionPane.showMessageDialog(null, "Data Saved");
            
        } catch (Exception e) {
             System.out.println("8");
            System.out.println("e");
        }
        tb_load();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField t_Customerid;
    private javax.swing.JTextField t_Driver_id;
    private javax.swing.JTextField t_Orderid;
    private javax.swing.JTextField t_Status;
    private javax.swing.JTextField t_TrackingNo;
    private javax.swing.JTextField t_Vehicleno;
    private javax.swing.JTextField t_location;
    // End of variables declaration//GEN-END:variables
}
