/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flightms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class EditTracking extends javax.swing.JFrame {

    /**
     * Creates new form EditTracking
     */
    public EditTracking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        space = new javax.swing.JTextField();
        ship = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, -1));

        id.setEditable(false);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, -1));

        date.setEditable(false);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 100, -1));

        space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceActionPerformed(evt);
            }
        });
        getContentPane().add(space, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 90, -1));

        ship.setEditable(false);
        getContentPane().add(ship, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 100, -1));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 100, -1));
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 80, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 90, 30));

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/ediiii.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //search
        
         String search1 = search.getText();
        
        try {
            Connection con = db.mycon();
            PreparedStatement pst = con.prepareStatement("select * from inventory.inventory where orderid = '"+search1+"'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                id.setText(rs.getString("orderid"));
                date.setText(rs.getString("recieved_date"));
                space.setText(rs.getString("storage"));
                ship.setText(rs.getString("shipment_method"));
                status.setText(rs.getString("status"));
                location.setText(rs.getString("location"));
                
            }
            
            
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         //update 
        String search1 = search.getText();
        String id1 = id.getText();
        String date1 = date.getText();
        String space1 = space.getText();
        String ship1 = ship.getText();
        String status1 = status.getText();
        String location1 = location.getText();
        
        try {
            Connection con = db.mycon();
            String sql ="update inventory.inventory set storage='"+space1+"', status ='"+status1+"' , location ='"+location1+"' where orderid = '"+search1+"' ";
            PreparedStatement pst = con.prepareStatement(sql);
            
            
            int updatedRowCount = pst.executeUpdate();
            
            
            
            JOptionPane.showMessageDialog(null, "Data Updated");
            
            
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         // delete
        
          String search1 = search.getText();
        
        try {
            Connection con = db.mycon();
            String sql ="delete from inventory.inventory where orderid = '"+search1+"' ";
            PreparedStatement pst = con.prepareStatement(sql);
            
            int updatedRowCount = pst.executeUpdate();
            
            
            
            JOptionPane.showMessageDialog(null, "Data Deleted");
            
            
            
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTracking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField search;
    private javax.swing.JTextField ship;
    private javax.swing.JTextField space;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
